---
- name: Configure Managed Node
  hosts: managed
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes